package Interfaces;

import DAO.EspecialidadDAO;
import DAO.MedicoDAO;
import DAO.PacienteDAO;
import DAO.TrabajadorDAO;
import Entidades.Especialidad;
import Entidades.Medico;
import Entidades.Paciente;
import Entidades.Trabajador;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author alexa
 */
public class Admin_Interface extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Interface
     */
    public Admin_Interface() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IDPaciente = new javax.swing.JTextField();
        txtDNIpaciente = new javax.swing.JTextField();
        txtNombrePaciente = new javax.swing.JTextField();
        txtApellidoPa = new javax.swing.JTextField();
        txtApellidoMa = new javax.swing.JTextField();
        txtFechaNac = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        BuscarPaciente_bttn = new javax.swing.JToggleButton();
        AgregarPaciente_btnn = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        IDMedico = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDNImedico = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNombreMedico = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtApellidoMa_med = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtApellidoPa_med = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtHora_entrada = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtSexo_med = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtTelefono_med = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtHora_Salida = new javax.swing.JTextField();
        BuscarMedico_bttn = new javax.swing.JToggleButton();
        AgregarMedico_btnn1 = new javax.swing.JToggleButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        EspecialidadList = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        buttn_Area = new javax.swing.JButton();
        MedicoLista = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtEspecialidad = new javax.swing.JTextField();
        buttonAgregarEspecialidad = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID del paciente");

        jLabel2.setText("DNI");

        jLabel3.setText("Nombre del Paciente");

        jLabel4.setText("Apellido Materno");

        jLabel5.setText("Apellido Paterno");

        jLabel6.setText("Fecha de Nacimiento");

        jLabel7.setText("Dirección del paciente");

        jLabel8.setText("Celular del paciente");

        txtNombrePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePacienteActionPerformed(evt);
            }
        });

        txtApellidoPa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPaActionPerformed(evt);
            }
        });

        txtApellidoMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMaActionPerformed(evt);
            }
        });

        BuscarPaciente_bttn.setText("Buscar Paciente");
        BuscarPaciente_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPaciente_bttnActionPerformed(evt);
            }
        });

        AgregarPaciente_btnn.setText("Agregar Paciente");
        AgregarPaciente_btnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPaciente_btnnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3)
                            .addGap(119, 119, 119))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDNIpaciente)
                                .addComponent(txtApellidoMa))
                            .addGap(36, 36, 36)))
                    .addComponent(IDPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoPa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelefono)
                            .addComponent(txtDireccion)
                            .addComponent(txtFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AgregarPaciente_btnn)
                                    .addComponent(BuscarPaciente_bttn))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDNIpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarPaciente_bttn))
                .addGap(8, 8, 8)
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoPa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarPaciente_btnn))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab1", jPanel6);

        jLabel9.setText("ID del médico");

        jLabel10.setText("DNI");

        jLabel11.setText("Nombre del Médico");

        txtNombreMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreMedicoActionPerformed(evt);
            }
        });

        jLabel12.setText("Apellido Materno del Médico");

        txtApellidoMa_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMa_medActionPerformed(evt);
            }
        });

        jLabel13.setText("Apellido Paterno del Médico");

        txtApellidoPa_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPa_medActionPerformed(evt);
            }
        });

        jLabel14.setText("Hora de entrada");

        jLabel15.setText("Sexo");

        jLabel16.setText("Celular");

        jLabel17.setText("Hora de salida");

        BuscarMedico_bttn.setText("Buscar Medico");
        BuscarMedico_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarMedico_bttnActionPerformed(evt);
            }
        });

        AgregarMedico_btnn1.setText("Agregar Medico");
        AgregarMedico_btnn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarMedico_btnn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(119, 119, 119))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDNImedico)
                                        .addComponent(txtApellidoMa_med, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(36, 36, 36)))
                            .addComponent(IDMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoPa_med, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel14))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHora_entrada, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(txtSexo_med)
                                    .addComponent(txtTelefono_med)
                                    .addComponent(txtHora_Salida)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)))))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AgregarMedico_btnn1)
                                    .addComponent(BuscarMedico_bttn)))))
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHora_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(9, 9, 9)
                        .addComponent(txtDNImedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(9, 9, 9)
                        .addComponent(txtHora_Salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(9, 9, 9)
                        .addComponent(txtNombreMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel12)
                        .addGap(9, 9, 9)
                        .addComponent(txtApellidoMa_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(9, 9, 9)
                        .addComponent(txtSexo_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel16)
                        .addGap(9, 9, 9)
                        .addComponent(txtTelefono_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(jLabel13)
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApellidoPa_med, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(BuscarMedico_bttn)
                        .addGap(33, 33, 33)
                        .addComponent(AgregarMedico_btnn1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab2", jPanel7);

        jLabel20.setText("Especialidad");

        EspecialidadList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel21.setText("Nombre Médico");

        buttn_Area.setText("Agregar Especialidad a Médico");
        buttn_Area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttn_AreaActionPerformed(evt);
            }
        });

        MedicoLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EspecialidadList, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MedicoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(buttn_Area)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel21)
                .addGap(9, 9, 9)
                .addComponent(MedicoLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel20)
                .addGap(9, 9, 9)
                .addComponent(EspecialidadList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(buttn_Area)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab3", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("tab4", jPanel9);

        jLabel18.setText("Agregar especialidad");

        txtEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecialidadActionPerformed(evt);
            }
        });

        buttonAgregarEspecialidad.setText("Agregar Especialidad");
        buttonAgregarEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarEspecialidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(buttonAgregarEspecialidad)
                        .addGap(112, 112, 112))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel18)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAgregarEspecialidad))
                .addContainerGap(302, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab5", jPanel2);

        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 550, 410));

        jButton1.setText("Medicos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Pacientes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Áreas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Citas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Especialidad");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(54, 54, 54)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jButton2)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addComponent(jButton3)
                .addGap(28, 28, 28)
                .addComponent(jButton4)
                .addGap(28, 28, 28)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTabbedPane2.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTabbedPane2.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTabbedPane2.setSelectedIndex(2);
        populateEspecialidadComboBox();
        populateMedicoComboBox();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTabbedPane2.setSelectedIndex(3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtNombrePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePacienteActionPerformed

    private void txtApellidoPaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPaActionPerformed

    private void txtApellidoMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMaActionPerformed
    private void populateEspecialidadComboBox() {
    EspecialidadDAO especialidadDAO = new EspecialidadDAO();

    List<Especialidad> especialidades = especialidadDAO.listarTodos();

    EspecialidadList.removeAllItems();

    for (Especialidad especialidad : especialidades) {
        EspecialidadList.addItem(especialidad.getNombre());
    }
    }
    
    private void populateMedicoComboBox() {
    MedicoDAO medicoDAO = new MedicoDAO();

    List<Medico> medico_lista = medicoDAO.listarTodos();

    MedicoLista.removeAllItems();

    for (Medico medico : medico_lista) {
        MedicoLista.addItem(medico.getNombres());
    }
    }
    
    private void EspecialidadMédicoAgregar(){
        try{
            String MedicoListaNombre = (String) MedicoLista.getSelectedItem();
            
            MedicoDAO medicoDAO = new MedicoDAO();
            String selectedMedicoNombre = (String) MedicoLista.getSelectedItem();
            int idMedico = medicoDAO.obtenerIdPorNombreMedico(selectedMedicoNombre);
            
            TrabajadorDAO trabajadorDAO = new TrabajadorDAO();
            String selectedEspecialidad = (String) EspecialidadList.getSelectedItem();
            
            int idEspecialidad = trabajadorDAO.obtenerIdPorNombreEspecialidad(selectedEspecialidad);   
            Trabajador trabajador = new Trabajador();
            trabajador.setId(0);
            trabajador.setIdEspecialidad(idEspecialidad);
            trabajador.setIdMedico(idMedico);
            buttn_Area.setSelected(false);
            trabajadorDAO.insertar(trabajador);
    
        } catch (NumberFormatException e) {
            System.out.println("Invalid ID format");
            buttonAgregarEspecialidad.setSelected(false);
        } catch (Exception e) {
            e.printStackTrace(); // or log the exception
            System.out.println("Error inserting paciente");
            buttonAgregarEspecialidad.setSelected(false);
        }
    }
    
    private void agregarEspecialidad(){
        try{
            String especi = txtEspecialidad.getText();
            Especialidad especialidad = new Especialidad();
            especialidad.setNombre(especi);
            buttonAgregarEspecialidad.setSelected(false);
            EspecialidadDAO especialidadDAO = new EspecialidadDAO();
            especialidadDAO.insertar(especialidad);
        } catch (NumberFormatException e) {
            System.out.println("Invalid ID format");
            buttonAgregarEspecialidad.setSelected(false);
        } catch (Exception e) {
            e.printStackTrace(); // or log the exception
            System.out.println("Error inserting paciente");
            buttonAgregarEspecialidad.setSelected(false);
        }
        
    }
    
    private Medico buscarMedicoPorId(int id) {
        MedicoDAO medicoDAO = new MedicoDAO();
        return medicoDAO.obtenerPorId(id);
    }
    
    private void llenarCamposMedico(Medico medico) {
        if (medico != null) {
            txtApellidoMa_med.setText(medico.getApellidoMaterno());
            txtApellidoPa_med.setText(medico.getApellidoPaterno());
            txtDNImedico.setText(medico.getDni());
            txtHora_Salida.setText(medico.getHoraSalida());
            txtHora_entrada.setText(medico.getHoraEntrada());
            txtNombreMedico.setText(medico.getNombres());
            txtSexo_med.setText(medico.getSexo());
            txtTelefono_med.setText(medico.getTelefono());
            
            BuscarMedico_bttn.setSelected(false);
        } else {
            System.out.println("Error: Invalid ID format");
            BuscarMedico_bttn.setSelected(false);
        }
    }
    
    private void buscarMedico() {
        int id = Integer.parseInt(IDMedico.getText());
        Medico medico = buscarMedicoPorId(id);
        llenarCamposMedico(medico);
    }
    
    private void agregarMedico() {
        try {
        int id = Integer.parseInt(IDMedico.getText());
        Medico medico = buscarMedicoPorId(id);
        
        if (medico != null) {
            System.out.println("Medic already exists");
            AgregarMedico_btnn1.setSelected(false);
        } else {
            String dni = txtDNImedico.getText();
            String nombres = txtNombreMedico.getText();
            String apellidoPaterno = txtApellidoPa_med.getText();
            String apellidoMaterno = txtApellidoMa_med.getText();
            String HoraSalida = txtHora_Salida.getText();
            String HoraEntrada = txtHora_entrada.getText();
            String celular = txtTelefono_med.getText();
            String Sexo = txtSexo_med.getText();
            System.out.println(id + "ID");
            
            Medico nuevomedico = new Medico();
            nuevomedico.setIdMedico(id);
            nuevomedico.setDni(dni);
            nuevomedico.setNombres(nombres);
            nuevomedico.setApellidoPaterno(apellidoPaterno);
            nuevomedico.setApellidoMaterno(apellidoMaterno);
            nuevomedico.setHoraEntrada(HoraEntrada);
            nuevomedico.setHoraSalida(HoraSalida);
            nuevomedico.setCelular(celular);
            nuevomedico.setSexo(Sexo);
            AgregarMedico_btnn1.setSelected(false);

            MedicoDAO medicoDAO = new MedicoDAO();
            medicoDAO.insertar(nuevomedico);
            System.out.println("Paciente inserted successfully");
            
        }
        
        } catch (NumberFormatException e) {
            System.out.println("Invalid ID format");
            AgregarMedico_btnn1.setSelected(false);
        } catch (Exception e) {
            e.printStackTrace(); // or log the exception
            System.out.println("Error inserting paciente");
            AgregarMedico_btnn1.setSelected(false);
        }
    }
    
    private Paciente buscarPacientePorId(int id) {
        PacienteDAO pacienteDAO = new PacienteDAO();
        return pacienteDAO.obtenerPorId(id);
    }

    private void llenarCamposPaciente(Paciente paciente) {
        if (paciente != null) {
            
            txtDNIpaciente.setText(paciente.getDni());
            txtApellidoMa.setText(paciente.getApellidoMaterno());
            txtApellidoPa.setText(paciente.getApellidoPaterno());
            txtDireccion.setText(paciente.getDireccion());
            txtFechaNac.setText(paciente.getFechaNacimiento());
            txtNombrePaciente.setText(paciente.getNombres());
            txtTelefono.setText(paciente.getCelular());
            BuscarPaciente_bttn.setSelected(false);
        } else {
            System.out.println("Error: Invalid ID format");
            BuscarPaciente_bttn.setSelected(false);
        }
    }

    private void buscarPaciente() {
        int id = Integer.parseInt(IDPaciente.getText());
        Paciente paciente = buscarPacientePorId(id);
        llenarCamposPaciente(paciente);
    }
    
    private void agregarPaciente() {
        PacienteDAO pacienteDAO = new PacienteDAO();
        try {
        int id = Integer.parseInt(IDPaciente.getText());
        Paciente paciente = buscarPacientePorId(id);
        
        if (paciente != null) {
            System.out.println("Paciente already exists");
            AgregarPaciente_btnn.setSelected(false);
        } else {
            String dni = txtDNIpaciente.getText();
            String nombres = txtNombrePaciente.getText();
            String apellidoPaterno = txtApellidoPa.getText();
            String apellidoMaterno = txtApellidoMa.getText();
            String fechaNacimiento = txtFechaNac.getText();
            String direccion = txtDireccion.getText();
            String celular = txtTelefono.getText();
            System.out.println(id + "ID");
            
            Paciente nuevoPaciente = new Paciente();
            nuevoPaciente.setIdPaciente(id);
            nuevoPaciente.setDni(dni);
            nuevoPaciente.setNombres(nombres);
            nuevoPaciente.setApellidoPaterno(apellidoPaterno);
            nuevoPaciente.setApellidoMaterno(apellidoMaterno);
            nuevoPaciente.setFechaNacimiento(fechaNacimiento);
            nuevoPaciente.setDireccion(direccion);
            nuevoPaciente.setCelular(celular);
            AgregarPaciente_btnn.setSelected(false);

            pacienteDAO.insertar(nuevoPaciente);
            System.out.println("Paciente inserted successfully");
            
        }
        
        } catch (NumberFormatException e) {
            System.out.println("Invalid ID format");
            AgregarPaciente_btnn.setSelected(false);
        } catch (Exception e) {
            e.printStackTrace(); // or log the exception
            System.out.println("Error inserting paciente");
            AgregarPaciente_btnn.setSelected(false);
        }
    }
    private void BuscarPaciente_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPaciente_bttnActionPerformed
        buscarPaciente();
    }//GEN-LAST:event_BuscarPaciente_bttnActionPerformed
        
    private void AgregarPaciente_btnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPaciente_btnnActionPerformed
        agregarPaciente();
        txtDNIpaciente.setText("");
        txtApellidoMa.setText("");
        txtApellidoPa.setText("");
        txtDireccion.setText("");
        txtFechaNac.setText("");
        txtNombrePaciente.setText("");
        txtTelefono.setText("");
    }//GEN-LAST:event_AgregarPaciente_btnnActionPerformed

    private void txtNombreMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMedicoActionPerformed

    private void txtApellidoMa_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMa_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMa_medActionPerformed

    private void txtApellidoPa_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPa_medActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPa_medActionPerformed

    private void BuscarMedico_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarMedico_bttnActionPerformed
        buscarMedico();
    }//GEN-LAST:event_BuscarMedico_bttnActionPerformed

    private void AgregarMedico_btnn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarMedico_btnn1ActionPerformed
        agregarMedico();
        IDMedico.setText("");
        txtApellidoMa_med.setText("");
        txtApellidoPa_med.setText("");
        txtDNImedico.setText("");
        txtHora_Salida.setText("");
        txtHora_entrada.setText("");
        txtNombreMedico.setText("");
        txtSexo_med.setText("");
        txtTelefono_med.setText("");
    }//GEN-LAST:event_AgregarMedico_btnn1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTabbedPane2.setSelectedIndex(4);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecialidadActionPerformed

    private void buttonAgregarEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarEspecialidadActionPerformed
        agregarEspecialidad();
    }//GEN-LAST:event_buttonAgregarEspecialidadActionPerformed

    private void buttn_AreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttn_AreaActionPerformed
        EspecialidadMédicoAgregar();
    }//GEN-LAST:event_buttn_AreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AgregarMedico_btnn1;
    private javax.swing.JToggleButton AgregarPaciente_btnn;
    private javax.swing.JToggleButton BuscarMedico_bttn;
    private javax.swing.JToggleButton BuscarPaciente_bttn;
    private javax.swing.JComboBox<String> EspecialidadList;
    private javax.swing.JTextField IDMedico;
    private javax.swing.JTextField IDPaciente;
    private javax.swing.JComboBox<String> MedicoLista;
    private javax.swing.JButton buttn_Area;
    private javax.swing.JButton buttonAgregarEspecialidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField txtApellidoMa;
    private javax.swing.JTextField txtApellidoMa_med;
    private javax.swing.JTextField txtApellidoPa;
    private javax.swing.JTextField txtApellidoPa_med;
    private javax.swing.JTextField txtDNImedico;
    private javax.swing.JTextField txtDNIpaciente;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtFechaNac;
    private javax.swing.JTextField txtHora_Salida;
    private javax.swing.JTextField txtHora_entrada;
    private javax.swing.JTextField txtNombreMedico;
    private javax.swing.JTextField txtNombrePaciente;
    private javax.swing.JTextField txtSexo_med;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono_med;
    // End of variables declaration//GEN-END:variables
}
